@startuml mutual funds cron recurring

participant "cron-recurring-enricher" as cre
participant "ms-investment-transaction" as mit
participant "ms-investment" as mi
collections "instructions" as instr

activate cre
cre -> cre: Run on 1, 3, 5am everyday
cre -> instr: query by enrichedAt ascending
cre -> mit: GET /admin/instructions/:recurringId
note right
{ 
    source: String
    cif: String
    recurringId: String
    productCode: String
    productName: String
    productGLAccount: String
    goalCode: String
    currency: String
    amount: Number
    fee: Number
    tax: Number
    createdAt: Date
    modifiedAt: Date
}
end note
activate mit
mit --> cre: productCode, goalCode\namount, fee, tax
deactivate mit
cre -> mi: GET /admin/products/:productCode
activate mi
cre -> mi: GET /admin/portfolios/:goalCode
mi --> cre: return imageUri, name, portfolioName
deactivate mi
cre -> instr: Update with enriched data
note right
{
    imageUri: String
    name: String
    beneficiaryName: String
    amount: Number
    enrichedAt: Date
}
end note
deactivate cre

@enduml