@startuml mutual funds cron recurring

participant "ms-investment" as mi
queue "ID.JENIUS.RECURRING.ENRICHER.MUTUAL_FUNDS" as kafka
participant "worker-recurring-enricher-investment" as wrei
collections "productInstructions" as prods
participant "ms-recurring" as instr

activate mi
mi -> kafka: Admin updates product\npublsh productCode, imageUri, and productName 
mi -> kafka: Users update portfolio\npublsh goalCode and portfolioName 
deactivate mi
kafka -> wrei: consume
note right
{ 
    productCode?: String, 
    goalCode?: String, 
    payload?: {
        imageUri: String
        productName: String
        portfolioName: String
    }
}
end note
activate wrei
wrei -> prods: query by \nproductCode and goalCode
note right
{ 
    source: String
    cif: String
    recurringId: String
    productCode: String
    productName: String
    productGLAccount: String
    goalCode: String
    currency: String
    amount: Number
    fee: Number
    tax: Number
    wreiatedAt: Date
    modifiedAt: Date
}
end note
activate prods
prods --> wrei: recurringIds: [String]
deactivate prods
wrei -> instr: PATCH /admin/instructions\nUpdate with enriched data
note right
{
    recurringIds: [String]
    payload: {
        imageUri: String
        name: String
        beneficiaryName: String
    }
}
end note
deactivate wrei

@enduml