@startuml mutual funds recurring

participant "ms-gql" as mg
participant "ms-investment-transaction" as mit
collections "productInstructions" as recSubs
participant "ms-recurring" as mr
collections "instructions" as recs

activate mg
mg -> mit: POST /instructions
note left
{ 
    frequency: ONCE/DAILY/DAILY_WEEKDAYS/WEEKLY/MONTHLY
    endCondition: DATE/OCCURENCE/NONE
    startDate: Date
    endDate?: Date
    targetOccurrence?: Number
    productCode: String
    goalCode: String
    amount: Number
    fee: Number
    tax: Number
}
end note
activate mit
mit -> mit: verify stepup
mit -> mr: POST /instructions
note right
{ 
    frequency: ONCE/DAILY/DAILY_WEEKDAYS/WEEKLY/MONTHLY
    endCondition: DATE/OCCURENCE/NONE
    startDate: Date
    endDate?: Date
    targetOccurrence?: Number
    amount: Number
    imageUri: String
    name: String
    beneficiaryName: String
    amount: Number
    category: String
    processingCode: MUTUAL_FUNDS_SUB
}
end note
activate mr
mr -> mr: executeDate = startDate
mr -> recs: insert instruction
note right
{ 
    cif: String
    recurringId: String
    frequency: ONCE/DAILY/DAILY_WEEKDAYS/WEEKLY/MONTHLY
    endCondition: DATE/OCCURENCE/NONE
    startDate: Date
    endDate?: Date
    targetOccurrence?: Number
    status: ACTIVE/PAUSED
    occurrence?: Number
    executeDate: Date
    processingCode: MUTUAL_FUNDS_SUB
    isProcessing: Boolean
    histories?: Array<{
        executedAt: Date
        status: SUCCESS/FAILED/INSUFFICIENT_BALANCE
    }>
    imageUri: String
    name: String
    beneficiaryName: String
    amount: Number
    category: String
    createdAt: Date
    modifiedAt: Date
}
end note
mr --> mit: return inserted data
deactivate mr
mit-> recSubs: insert recurring subscription
note right
{ 
    cif: String
    recurringId: String
    productCode: String
    goalCode: String
    amount: Number
    fee: Number
    tax: Number
    createdAt: Date
    modifiedAt: Date
}
end note
mit --> mg: return detailed recurring data
deactivate mit
deactivate mg

@enduml