@startuml monitoring
participant "Apps" as app
participant "BTPN\nJenius Microservices" as ms
collections "DB Investment" as db
participant "Additiv\nDFS" as dfs

activate app
app -> ms: query bondsMonitoringList
deactivate app

@enduml