@startuml switchtransactions
participant "Additiv\nDFS" as dfs
queue "BTPN\nKafka" as kafka
participant "worker-investment-transaction" as ms
collections "DB Investment\nTransaction" as db
participant "ms-investment" as mi

activate dfs
dfs -> kafka: publish status Verified transaction\nID.DFS.INVESTMENT.TRANSACTION.STATUS
note left
{
  "Status": "Verified",
  "Channel": "Jenius",
  "CIF": "2458O7",
  "ReferenceNumber": "XXXX1XX1",
  "FailReason": "InsufficientMinimumSwitchOutUnits",
  "PortfolioId": 1374
  "TransactionCategory": "Switching",
  "TransactionDate": "2022-07-13T10:39:35",
  "SettlementDate": "2022-07-13T10:39:35",
  "TransactionId": 1274,
  "SwitchIn": {
    "ProductIsin": "IDG000015108",
    "ProductCurrency": "IDR",
    "NAVDate": "2022-07-13T10:39:35",
    "NAV": 6442.307,
    "Units": 1.56,
    "InvestmentAmount": 100500
  },
  "SwitchOut": {
    "ProductIsin": "IDG000015107",
    "ProductCurrency": "IDR",
    "NAVDate": "2022-07-13T10:39:35",
    "NAV": 6442.307,
    "Units": 1.56,
    "InvestmentAmount": 100489
  },
  "FeeAmount": 10,
  "TaxAmount": 1
}
end note
activate kafka
kafka --> ms: consume Verified status
deactivate kafka
activate ms
ms -> mi: GET /portfolios?portfolioId=
activate mi
mi --> ms: return portfolio name, goalCode
deactivate mi
ms -> db: Update database inflightTransaction\nreferenceNo+SWTOUT
note right
cif: String
status: Status <- from kafka
failReason: FailReason <- from kafka
type: TransactionCategory <- from kafka
amount: InvestmentAmount <- from kafka
fee: FeeAmount <- from kafka
tax: TaxAmount <- from kafka
units: Units <- from kafka
referenceNo: String
navDate: NAVDate <- from kafka
createdAt: TransactionDate <- from kafka
modifiedAt: SettlementDate <- from kafka
currency: ProductCurrency <- from kafka
portfolioId: PortfolioId <- from kafka
productIsin: ProductIsin <- from kafka
navPerUnit: Number
productCode: String
goalCode: String
productName: String
portfolioName: String <- from get porto
imageUri: String
assetClass: Number
source: Number
end note
ms -> db: Update database inflightTransaction\nreferenceNo+SWTIN
note right
cif: String
status: Status <- from kafka
failReason: FailReason <- from kafka
type: TransactionCategory <- from kafka
amount: InvestmentAmount <- from kafka
fee: FeeAmount <- from kafka
tax: TaxAmount <- from kafka
units: Units <- from kafka
referenceNo: String
navDate: NAVDate <- from kafka
createdAt: TransactionDate <- from kafka
modifiedAt: SettlementDate <- from kafka
currency: ProductCurrency <- from kafka
portfolioId: PortfolioId <- from kafka
productIsin: ProductIsin <- from kafka
navPerUnit: Number
productCode: String
goalCode: String
productName: String
portfolioName: String <- from get porto
imageUri: String
assetClass: Number
source: Number
end note
ms -> mi: DELETE /admin/portfolios-cache/:cif
deactivate ms

dfs -> dfs: PTWS receive transaction report from KSEI
dfs -> kafka: publish status Settled transaction\nwith calculated units\nto ID.DFS.INVESTMENT.TRANSACTION.STATUS
activate kafka
kafka --> ms: consume Settled status
deactivate kafka
activate ms
ms -> mi: GET /portfolios?portfolioId=
ms -> db: Update database inflightTransaction\nSWTIN & SWTOUT
ms -> mi: DELETE /admin/portfolios-cache/:cif
deactivate ms

opt If transaction failed
dfs -> kafka: publish status Failed transaction\nto ID.JENIUS.INVESTMENT.TRANSACTION.STATUS
activate kafka
kafka --> ms: consume Failed status
deactivate kafka
activate ms
ms -> mi: GET /portfolios?portfolioId=
ms -> db: Update database inflightTransaction\nSWTIN & SWTOUT
ms -> mi: DELETE /admin/portfolios-cache/:cif
deactivate ms
end opt

deactivate dfs

@enduml