@startuml bancassurance
participant "Apps" as app
participant "ms-portfolio" as ms
participant "ms-forex" as forex
participant "Additiv\nDFS" as dfs

activate app
app -> ms: GraphQL query bancassurance
note right
assets {
  bancassurance {
    total
    products {
      originalAmount
      productName
      fundName
      navPerUnitAmount
      navDate
      totalUnitCount
      originalCcyCode
    }
  }
}
end note
activate ms

ms -> forex: GET /foreign-exchanges/rates
activate forex
forex --> ms: return forex rates
deactivate forex

ms -> dfs: GET /btpnCustomServiceLayer/v1/contacts/{contactId}/portfolio-bancassurance
activate dfs
dfs --> ms: return bancassurance data
note right
{
  "Id": 2426,
  "UId": "51ec77d3-db86-4796-a7d1-267f7326c897",
  "ExternalId": "BAN_21984W",
  "Name": "BAN_21984W",
  "Positions": [
    {
      "Id": 19616,
      "Security": {
        "Id": 283,
        "Name": "GUARDIA PREMIUM",
        "Isin": "BASE_GUPR",
        "Currency": {
          "Id": 34,
          "Name": "Indonesian Rupiah",
          "CurrencyCode": "IDR",
          "Symbol": "Rp"
        }
      },
      "Quantity": 5823.364,
      "InvestmentValuePortfolioCurrency": 22887509.3,
      "InvestmentValueSecurityCurrency": 22887509.3,
      "FundSecurity": {
        "Id": 353,
        "Name": "Smartlink Rupiah Balanced Fund",
        "Isin": "BF",
        "Currency": {
          "Id": 34,
          "Name": "Indonesian Rupiah",
          "CurrencyCode": "IDR",
          "Symbol": "Rp"
        },
        "ValuationDate": "2022-07-20T00:00:00",
        "ValuationPrice": 3930.29
      }
    }
  ]
}
end note
deactivate dfs
ms -> ms: calculate total with Jenius forex rates
ms --> app: return bancassurance
deactivate ms
deactivate app

@enduml