@startuml open account
participant "Apps" as app
participant "ms-gql" as gql
participant "ms-investment" as ms
collections "DB Investment" as db
participant "ms-user-preference" as mup
participant "ms-accounts" as ma
queue "BTPN\nKafka" as kafka
participant "Additiv\nDFS" as dfs

activate app
app -> ms: GraphQL mutation\nregisterInvestmentAccount
note right
registerInvestmentAccount(input: RegisterInvestmentAccountInput!)
input RegisterInvestmentAccountInput {
  education: String!
}
end note
activate ms

ms -> mup: GET /profile
activate mup
mup --> ms: return profile
deactivate mup

ms -> ma: GET /accounts
activate ma
ma --> ms: return bank accounts
deactivate ma

ms -> ms: map profile data
ms -> kafka: Publish customer data\nID.DFS.INVESTMENT.OPEN_ACCOUNT.REQUEST
note right
{ 
  "ChannelID ": "02",
  "CIF": "2458O7",
  "CustomerData":  { 
    "Name": "Loyal Customer",
    "DOB": "1970-01-01",
    "Sex": "L",
    "Religion": "1",
    "Education": "4",
    "PlaceOfBirth": "JAKARTA",
    "Nationality": "ID",
    "Marital": "2",
    "IdCardNo": "123124565750008",
    "IdCardType": "1",
    "ExpiredDate": "2025-01-01",
    "TaxNo": "",
    "OccupationSubject": "15-Non Formal Lainnya",
    "MainIncomeGrossPerYear": "4",
    "SourceMainIncome": "1",
    "Objective": "1",
    "Email": "TEST3984@BTPN.COM",
    "MobilePhoneNo": "08595849484",
    "address": [
      { 
        "PhoneNo": "", 
        "Address": "JL. PRAMUKA NO 201 KEMANG MAMPANG",
        "AddressType": "1",
        "Country": "ID",
        "City": "0395",
        "KodePos": "22910"
      },
      { 
        "PhoneNo": "", 
        "Address": "GREEN VILLE BLOK",
        "AddressType": "2",
        "Country": "ID",
        "City": "0395",
        "KodePos": "12180"
      }
    ],
    "bankAccount": [
      { 
        "BranchCode": "0019",
        "BranchName": "KC YOGYAKARTA",
        "AccountType": "EG",
        "Currency": "IDR",
        "AccountNo": "00193000061",
        "AccountName": "TESTING 20"
      },
      { 
        "BranchCode": "0002",
        "BranchName": "KANTOR Cabang Jakarta",
        "AccountType": "EL",
        "Currency": "USD",
        "AccountNo": "04610004423",
        "AccountName": "widi test 2"
      }
    ]
  },
  "actionType": "C"
}
end note
activate kafka
kafka --> dfs: consume register account
deactivate kafka
ms --> app: response request accepted
ms -> db: update status=VERIFYING
ms -> db: create inflight account
ms -> mup: PATCH /profile/additional-info\nupdate education
deactivate ms
deactivate app
deactivate ms
deactivate kafka

@enduml